Switch to gh actions for deploys
This requires specifying a version of ruby

DOESN'T WORK:

Run actions/configure-pages@v5
  with:
    token: ***
    enablement: false
Error: Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action. Error: Not Found - https://docs.github.com/rest/pages/pages#get-a-apiname-pages-site
Error: HttpError: Not Found - https://docs.github.com/rest/pages/pages#get-a-apiname-pages-site

I guess that gh actions script only works for the base page?